package:
  name: hyperledger-fabric-peer
  version: 2.5.0
  epoch: 0
  description: A package for a Hyperledger Fabric Peer
  target-architecture: [x86_64, aarch64]
  copyright:
    - license: Apache-2.0

environment:
  environment:
    GOMODCACHE: '/var/cache/melange'
  contents:
    keyring:
      - https://packages.wolfi.dev/os/wolfi-signing.rsa.pub
    repositories:
      - https://packages.wolfi.dev/os
    packages:
      - wolfi-base
      - ca-certificates-bundle
      - go

vars:
  bindir: /build/bin/peer
  fabriccfg: /etc/hyperledger/fabric
  repourl: https://github.com/hyperledger/fabric

pipeline:
  - uses: git-checkout
    with:
      repository: ${{vars.repourl}}
      tag: v${{package.version}}

  - runs: |
      COMMIT_SHA=$(git rev-parse HEAD)
      echo "$COMMIT_SHA" > ${{targets.destdir}}/commit_sha.txt

  - runs: |
      mkdir -p ${{targets.destdir}}${{vars.fabriccfg}}/msp \
               ${{targets.destdir}}${{vars.bindir}} \
               ${{targets.destdir}}/var/hyperledger/production \
               ${{targets.destdir}}/release/${{build.arch}}/builders/ccaas/bin/ \
               ${{targets.destdir}}/opt/hyperledger/ccaas_builder/bin \
               ${{targets.destdir}}/usr/local/bin

  - runs: |
      cd ccaas_builder
      go build -buildvcs=false \
        -o ${{targets.destdir}}/release/${{build.arch}}/builders/ccaas/bin/ ./cmd/release/

  - runs: |
      set -ex
      export GOBIN=${{targets.destdir}}${{vars.bindir}}
      CGO_CFLAGS=" " go install -tags "" -ldflags "\
        -X github.com/hyperledger/fabric/common/metadata.Version=${{package.version}} \
        -X github.com/hyperledger/fabric/common/metadata.CommitSHA=$(cat ${{targets.destdir}}/commit_sha.txt) \
        -X github.com/hyperledger/fabric/common/metadata.BaseDockerLabel=org.hyperledger.fabric \
        -X github.com/hyperledger/fabric/common/metadata.DockerNamespace=hyperledger \
        -X github.com/hyperledger/fabric/common/metadata.BaseDockerNamespace=hyperledger" \
        -buildvcs=false github.com/hyperledger/fabric/cmd/peer

  - runs: |
      cp -r sampleconfig/msp "${{targets.destdir}}${{vars.fabriccfg}}/"
      cp sampleconfig/core.yaml "${{targets.destdir}}${{vars.fabriccfg}}/core.yaml"
      cp -r ${{targets.destdir}}${{vars.bindir}}/peer ${{targets.destdir}}/usr/local/bin/
      cp -r ${{targets.destdir}}/release/${{build.arch}}/builders/ccaas/bin ${{targets.destdir}}/opt/hyperledger/ccaas_builder/

  - uses: strip
